version: '3'

services: 
    website: 
        build: .
        image: min:tag
        command: python proj/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
            - "5001:8000"    